"""
Lal Kitab Remedies — Planet-in-House based remedial measures.
Bilingual: Hindi + English.
"""
from __future__ import annotations
from dataclasses import dataclass


@dataclass
class LalKitabRemedy:
    planet: str
    house: int
    effect_en: str
    effect_hi: str
    remedies_en: list[str]
    remedies_hi: list[str]
    donate_en: list[str]
    donate_hi: list[str]
    avoid_en: list[str]
    avoid_hi: list[str]


def _b(p, h, d):
    return LalKitabRemedy(p, h, d[0], d[1], d[2], d[3], d[4], d[5], d[6], d[7])


def get_lal_kitab_remedies(planet_houses: dict[str, int]) -> list[LalKitabRemedy]:
    """Return Lal Kitab remedies for all planets based on their house placement."""
    results = []
    for planet, house in planet_houses.items():
        data = _PLANET_DATA.get(planet, {}).get(house)
        if data:
            results.append(_b(planet, house, data))
    return results


# Format per entry: (effect_en, effect_hi, [remedies_en], [remedies_hi], [donate_en], [donate_hi], [avoid_en], [avoid_hi])
_PLANET_DATA = {
  "Sun": {
    1: ("Strong leadership, govt favours", "नेतृत्व मजबूत, सरकारी कृपा",
        ["Offer water to Sun at sunrise", "Wear ruby/copper ring"], ["सूर्योदय पर जल अर्पण", "माणिक/तांबे की अंगूठी"],
        ["Wheat", "Jaggery", "Copper"], ["गेहूं", "गुड़", "तांबा"], ["Do not accept free items"], ["मुफ्त वस्तुएं न लें"]),
    2: ("Good wealth, ego in family", "अच्छा धन, परिवार में अहंकार",
        ["Keep solid silver at home", "Respect father"], ["घर में चांदी रखें", "पिता का सम्मान"],
        ["Wheat", "Jaggery"], ["गेहूं", "गुड़"], ["Don't take free things"], ["मुफ्त न लें"]),
    3: ("Courageous, sibling troubles", "साहसी, भाई-बहन कठिनाई",
        ["Feed jaggery to monkeys", "Saffron tilak"], ["बंदरों को गुड़", "केसर तिलक"],
        ["Wheat", "Copper coins in river"], ["गेहूं", "नदी में तांबे सिक्के"], ["Avoid meat/alcohol"], ["मांस/शराब बचें"]),
    4: ("Property/mother health issues", "संपत्ति/माता स्वास्थ्य समस्या",
        ["Wheat+copper in kitchen", "Serve father"], ["रसोई गेहूं-तांबा", "पिता सेवा"],
        ["Wheat to temple"], ["मंदिर गेहूं"], ["No begging donations at door"], ["दरवाजे दान न दें"]),
    5: ("Good education & children", "शिक्षा-संतान अच्छी",
        ["Water+jaggery to Sun", "Almonds on desk"], ["गुड़-जल सूर्य को", "मेज बादाम"],
        ["Saffron", "Education materials"], ["केसर", "शैक्षिक सामग्री"], ["No gambling if afflicted"], ["पीड़ित हो तो जुआ बचें"]),
    6: ("Victory, eye/bone issues", "विजय, आंख/हड्डी समस्या",
        ["Feed monkey", "Copper vessel"], ["बंदर खिलाएं", "तांबा बर्तन"],
        ["Wheat flour to fish"], ["मछलियों आटा"], ["No broken mirror"], ["टूटा शीशा न रखें"]),
    7: ("Late marriage, dominant spouse", "देर विवाह, प्रभावी साथी",
        ["Copper in pocket", "Water to Sun"], ["जेब तांबा", "सूर्य को जल"],
        ["Wheat to poor"], ["गरीबों गेहूं"], ["No spouse conflicts"], ["साथी से टकराव बचें"]),
    8: ("Hidden enemies, inheritance dispute", "छिपे शत्रु, विरासत विवाद",
        ["Silver at home", "Saffron tilak"], ["घर चांदी", "केसर तिलक"],
        ["Copper to temple"], ["मंदिर तांबा"], ["No free food from strangers"], ["अजनबी मुफ्त भोजन बचें"]),
    9: ("Father fortune, religious", "पिता भाग्य, धार्मिक",
        ["Sunday Sun temple", "Copper at worship"], ["रविवार सूर्य मंदिर", "पूजा तांबा"],
        ["Wheat+jaggery Sunday temple"], ["रविवार मंदिर गेहूं-गुड़"], ["Respect father/guru"], ["पिता/गुरु सम्मान"]),
    10: ("Excellent career, govt job", "उत्कृष्ट करियर, सरकारी नौकरी",
        ["Water to Sun sunrise", "Copper ring"], ["सूर्योदय जल", "तांबे अंगूठी"],
        ["Wheat", "Red flowers"], ["गेहूं", "लाल फूल"], ["No non-veg Sunday"], ["रविवार मांसाहार बचें"]),
    11: ("Good income, multiple sources", "अच्छी आय, अनेक स्रोत",
        ["Daily water to Sun", "Copper coin wallet"], ["प्रतिदिन सूर्य जल", "बटुए तांबा सिक्का"],
        ["Jaggery Sundays"], ["रविवार गुड़"], ["No arrogance"], ["अहंकार बचें"]),
    12: ("Govt expenses, eye problems", "सरकारी खर्च, आंख समस्या",
        ["Jaggery water near bed night"], ["रात बिस्तर गुड़-पानी"],
        ["Wheat temple", "Alms to blind"], ["मंदिर गेहूं", "अंधों दान"], ["Keep home lit"], ["घर रोशन रखें"]),
  },
  "Moon": {
    1: ("Imaginative, emotional, good PR", "कल्पनाशील, भावनात्मक",
        ["Silver ball pocket", "Silver glass water", "Respect mother"], ["जेब चांदी गोली", "चांदी गिलास", "माता सम्मान"],
        ["Rice", "Milk", "White cloth"], ["चावल", "दूध", "सफेद कपड़ा"], ["Don't sell milk"], ["दूध न बेचें"]),
    2: ("Family wealth, good memory", "पारिवारिक धन, अच्छी स्मृति",
        ["Silver at home", "Milk Shiv temple"], ["घर चांदी", "शिव मंदिर दूध"],
        ["Rice+milk to poor"], ["गरीबों चावल-दूध"], ["Don't sell ancestral property"], ["पैतृक संपत्ति न बेचें"]),
    3: ("Creative, short travels", "रचनात्मक, छोटी यात्राएं",
        ["Silver chain", "White flowers temple"], ["चांदी चेन", "मंदिर सफेद फूल"],
        ["Rice", "Camphor"], ["चावल", "कपूर"], ["No negative self-talk"], ["नकारात्मक बातचीत बचें"]),
    4: ("Mother's blessings protect", "माता आशीर्वाद रक्षा",
        ["Silver square home", "Monday milk Shivling"], ["घर चांदी चौकोर", "सोमवार शिवलिंग दूध"],
        ["Milk", "Rice old-age home"], ["दूध", "वृद्धाश्रम चावल"], ["Respect elderly women"], ["बुजुर्ग महिलाओं सम्मान"]),
    5: ("Emotional intelligence, children good", "भावनात्मक बुद्धि, संतान अच्छी",
        ["Feed white cows", "Wear pearl"], ["सफेद गायों खिलाएं", "मोती पहनें"],
        ["White clothes to Brahmin"], ["ब्राह्मण सफेद कपड़े"], ["No deceit"], ["छल बचें"]),
    6: ("Mental anxiety, stomach", "मानसिक चिंता, पेट",
        ["Silver pocket", "Monday temple milk"], ["जेब चांदी", "सोमवार मंदिर दूध"],
        ["Rice", "Milk"], ["चावल", "दूध"], ["No stale food"], ["बासी भोजन बचें"]),
    7: ("Caring spouse, good marriage", "देखभाल साथी, अच्छा विवाह",
        ["Silver to spouse", "Silver glass"], ["जीवनसाथी चांदी", "चांदी गिलास"],
        ["White clothes"], ["सफेद कपड़े"], ["No affairs"], ["विवाहेतर संबंध बचें"]),
    8: ("Emotional turbulence", "भावनात्मक उथल-पुथल",
        ["Silver pot honey", "Monday rice river"], ["चांदी बर्तन शहद", "सोमवार नदी चावल"],
        ["Milk to snake temple"], ["नाग मंदिर दूध"], ["No stagnant water home"], ["घर रुका पानी बचें"]),
    9: ("Fortune through mother", "माता से भाग्य",
        ["Monday rice temple"], ["सोमवार मंदिर चावल"],
        ["Rice+white sweets temple"], ["मंदिर चावल-सफेद मिठाई"], ["Never speak ill of mother"], ["माता बुराई न करें"]),
    10: ("Career public/govt", "करियर जनसंपर्क/सरकार",
        ["Pearl/silver ring", "Milk silver vessel"], ["मोती/चांदी अंगूठी", "चांदी बर्तन दूध"],
        ["Milk to poor"], ["गरीबों दूध"], ["Work for public good"], ["जनहित कार्य"]),
    11: ("Gains through women", "महिलाओं से लाभ",
        ["Silver items", "Durga temple milk"], ["चांदी", "दुर्गा मंदिर दूध"],
        ["White cloth", "Rice poor"], ["सफेद कपड़ा", "गरीबों चावल"], ["No manipulation"], ["छल बचें"]),
    12: ("Sleep disturbance, isolation", "नींद बाधा, अलगाव",
        ["Rainwater silver vessel", "Shiv temple milk"], ["चांदी बारिश पानी", "शिव मंदिर दूध"],
        ["Monday rice+milk poor"], ["सोमवार गरीबों चावल-दूध"], ["Water near pillow"], ["तकिए पास पानी"]),
  },
  "Mars": {
    1: ("Aggressive, leadership, anger", "आक्रामक, नेतृत्व, क्रोध",
        ["Copper ring", "Sweet chapati dogs"], ["तांबे अंगूठी", "कुत्तों मीठी रोटी"],
        ["Red lentils", "Jaggery"], ["मसूर", "गुड़"], ["Avoid anger"], ["क्रोध बचें"]),
    2: ("Harsh speech, dental issues", "कड़वी वाणी, दांत",
        ["Sweet bread dogs", "Red handkerchief"], ["कुत्तों मीठी रोटी", "लाल रुमाल"],
        ["Masoor dal", "Honey"], ["मसूर", "शहद"], ["Gentle speech about money"], ["पैसों मधुर वाणी"]),
    3: ("Brave, good siblings", "बहादुर, भाई-बहन अच्छे",
        ["Red handkerchief", "Donate blood"], ["लाल रुमाल", "रक्तदान"],
        ["Red lentils"], ["मसूर"], ["Kind to younger ones"], ["छोटों से दयालु"]),
    4: ("Property disputes, mother health", "संपत्ति विवाद, माता स्वास्थ्य",
        ["Silver square", "Saffron tilak", "Dogs sweet roti"], ["चांदी चौकोर", "केसर तिलक", "कुत्तों मीठी रोटी"],
        ["Red cloth Hanuman temple"], ["हनुमान मंदिर लाल कपड़ा"], ["No open weapons home"], ["खुले हथियार घर बचें"]),
    5: ("Sharp intellect, sports good", "तीक्ष्ण बुद्धि, खेल अच्छा",
        ["Daily saffron tilak", "Jaggery chapati dogs"], ["केसर तिलक", "कुत्तों गुड़ रोटी"],
        ["Pomegranate", "Red flowers"], ["अनार", "लाल फूल"], ["No speculation if weak"], ["कमजोर हो तो सट्टा बचें"]),
    6: ("Victory, good stamina", "विजय, अच्छी सहनशक्ति",
        ["Daily sweet chapati dogs", "Coral ring"], ["कुत्तों मीठी रोटी", "मूंगा अंगूठी"],
        ["Red lentils poor"], ["गरीबों मसूर"], ["Kind to animals"], ["पशुओं दयालु"]),
    7: ("Mangal Dosha, marriage challenges", "मंगल दोष, विवाह चुनौती",
        ["Tuesday sweets Hanuman temple"], ["मंगलवार हनुमान मंदिर मिठाई"],
        ["Red cloth", "Tuesday sweets"], ["लाल कपड़ा", "मंगलवार मिठाई"], ["No spouse fights"], ["साथी से न लड़ें"]),
    8: ("Accidents, surgery, enemies", "दुर्घटना, शल्य, शत्रु",
        ["Float red masoor river", "Sweet bread dogs"], ["नदी मसूर", "कुत्तों रोटी"],
        ["Red lentils"], ["मसूर"], ["Avoid risk", "No rusted iron home"], ["जोखिम बचें", "जंग लोहा घर बचें"]),
    9: ("Religious warrior, pilgrimages", "धार्मिक योद्धा, तीर्थयात्रा",
        ["Tuesday Hanuman temple", "Red tilak"], ["मंगलवार हनुमान मंदिर", "लाल तिलक"],
        ["Red flowers temple"], ["मंदिर लाल फूल"], ["Respect elders"], ["बड़ों सम्मान"]),
    10: ("Military/police/engineering career", "सेना/पुलिस/इंजीनियरिंग करियर",
        ["Coral ring finger", "Sindoor Hanuman"], ["अनामिका मूंगा", "हनुमान सिंदूर"],
        ["Sindoor", "Red cloth"], ["सिंदूर", "लाल कपड़ा"], ["Channel energy well"], ["ऊर्जा सही दिशा"]),
    11: ("Gains brothers/property", "भाइयों/संपत्ति लाभ",
        ["Feed dogs", "Copper home"], ["कुत्तों खिलाएं", "घर तांबा"],
        ["Red lentils"], ["मसूर"], ["Don't cheat brothers"], ["भाइयों धोखा बचें"]),
    12: ("Hidden anger, legal expense", "छिपा क्रोध, कानूनी खर्च",
        ["Float red items river", "Sweet bread dogs"], ["नदी लाल वस्तुएं", "कुत्तों रोटी"],
        ["Masoor dal river"], ["नदी मसूर"], ["No sharp weapons home"], ["तेज हथियार घर बचें"]),
  },
  "Mercury": {
    1: ("Intelligent, good business", "बुद्धिमान, व्यापार अच्छा",
        ["Emerald/green ring", "Green moong birds"], ["पन्ना/हरी अंगूठी", "पक्षियों हरी मूंग"],
        ["Green vegetables", "Moong dal"], ["हरी सब्जियां", "मूंग"], ["No lying"], ["झूठ बचें"]),
    2: ("Wealth through intellect", "बुद्धि से धन",
        ["Green cloth wallet", "Donate to schools"], ["बटुए हरा कपड़ा", "स्कूल दान"],
        ["Green moong", "Books"], ["हरी मूंग", "पुस्तकें"], ["No false accounts"], ["झूठे खाते बचें"]),
    3: ("Writing/media/IT career", "लेखन/मीडिया/आईटी करियर",
        ["Green ring", "Green plant desk"], ["हरी अंगूठी", "मेज हरा पौधा"],
        ["Green dal poor"], ["गरीबों हरी दाल"], ["No gossip"], ["गपशप बचें"]),
    4: ("Good education, home", "अच्छी शिक्षा, घर",
        ["Emerald worship place", "Green plants home"], ["पूजा पन्ना", "घर हरे पौधे"],
        ["Green vegetables temple"], ["मंदिर हरी सब्जी"], ["No caged parrots"], ["पिंजरे तोते बचें"]),
    5: ("Sharp mind, studies", "तीक्ष्ण बुद्धि, पढ़ाई",
        ["Green grass cows", "Emerald"], ["गायों हरा चारा", "पन्ना"],
        ["Books students"], ["छात्रों पुस्तकें"], ["Don't mislead children"], ["बच्चों गुमराह बचें"]),
    6: ("Victory intelligence, skin", "बुद्धि विजय, त्वचा",
        ["Green moong birds"], ["पक्षियों हरी मूंग"],
        ["Green dal poor"], ["गरीबों हरी दाल"], ["Kind to workers"], ["कामगारों दयालु"]),
    7: ("Good partnership, smart spouse", "अच्छी साझेदारी, बुद्धिमान साथी",
        ["Green items spouse"], ["जीवनसाथी हरी वस्तुएं"],
        ["Green cloth newlyweds"], ["नवविवाहितों हरा कपड़ा"], ["Honest partnerships"], ["साझेदारी ईमानदार"]),
    8: ("Nervous disorders, hidden knowledge", "तंत्रिका, गुप्त ज्ञान",
        ["Float green moong river", "Iron ring"], ["नदी हरी मूंग", "लोहे अंगूठी"],
        ["Green items flowing water"], ["बहते पानी हरी वस्तुएं"], ["No parrot home"], ["घर तोता बचें"]),
    9: ("Fortune intellect/guru", "बुद्धि/गुरु भाग्य",
        ["Wednesday green items temple"], ["बुधवार मंदिर हरी वस्तुएं"],
        ["Aids poor students"], ["गरीब छात्रों सहायता"], ["Respect teachers"], ["शिक्षक सम्मान"]),
    10: ("Career: IT/business/media", "करियर: आईटी/व्यापार/मीडिया",
        ["Emerald little finger"], ["कनिष्ठा पन्ना"],
        ["Books libraries"], ["पुस्तकालय पुस्तकें"], ["No fraud"], ["धोखाधड़ी बचें"]),
    11: ("Business/networking gains", "व्यापार/नेटवर्किंग लाभ",
        ["Emerald", "Green dal poor"], ["पन्ना", "गरीबों हरी दाल"],
        ["Wednesday moong dal"], ["बुधवार मूंग"], ["Don't cheat friends"], ["मित्रों धोखा बचें"]),
    12: ("Education expense, anxiety", "शिक्षा खर्च, चिंता",
        ["Float green moong river"], ["नदी हरी मूंग"],
        ["Books prisoners"], ["कैदियों पुस्तकें"], ["Avoid isolation"], ["अलगाव बचें"]),
  },
  "Jupiter": {
    1: ("Wise, religious, blessed", "बुद्धिमान, धार्मिक, धन्य",
        ["Saffron tilak", "Pukhraj", "Respect teachers"], ["केसर तिलक", "पुखराज", "शिक्षक सम्मान"],
        ["Chana dal", "Turmeric", "Bananas"], ["चना दाल", "हल्दी", "केले"], ["Respect holy books"], ["पवित्र पुस्तक सम्मान"]),
    2: ("Wealthy, generous, good speech", "धनी, उदार, अच्छी वाणी",
        ["Saffron tilak", "Donate temples/schools"], ["केसर तिलक", "मंदिर/स्कूल दान"],
        ["Thursday yellow items"], ["गुरुवार पीली वस्तुएं"], ["Never cut Peepal"], ["पीपल न काटें"]),
    3: ("Religious courage", "धार्मिक साहस",
        ["Turmeric tilak", "Thursday temple"], ["हल्दी तिलक", "गुरुवार मंदिर"],
        ["Yellow flowers", "Bananas"], ["पीले फूल", "केले"], ["No alcohol"], ["शराब बचें"]),
    4: ("Blessed home, religious mother", "धन्य घर, धार्मिक माता",
        ["Saffron home", "Thursday Peepal water"], ["घर केसर", "गुरुवार पीपल पानी"],
        ["Yellow sweets Brahmins"], ["ब्राह्मणों पीली मिठाई"], ["Respect mother/guru"], ["माता/गुरु सम्मान"]),
    5: ("Good children, education", "अच्छे बच्चे, शिक्षा",
        ["Saffron tilak children", "Yellow thread"], ["बच्चों केसर तिलक", "पीला धागा"],
        ["Bananas monkeys"], ["बंदरों केले"], ["Kind to children"], ["बच्चों दयालु"]),
    6: ("Liver issues, hidden enemies", "यकृत, छिपे शत्रु",
        ["Turmeric tilak"], ["हल्दी तिलक"],
        ["Chana dal dogs"], ["कुत्तों चना दाल"], ["No religious arrogance"], ["धर्म अहंकार बचें"]),
    7: ("Wise spouse", "बुद्धिमान साथी",
        ["Yellow items spouse", "Saffron tilak"], ["जीवनसाथी पीली वस्तुएं", "केसर तिलक"],
        ["Yellow cloth newlyweds"], ["नवविवाहितों पीला कपड़ा"], ["Respect spouse belief"], ["साथी मान्यता सम्मान"]),
    8: ("Longevity, hidden spiritual knowledge", "दीर्घायु, गुप्त ज्ञान",
        ["Saffron tilak navel", "Temple turmeric"], ["नाभि केसर", "मंदिर हल्दी"],
        ["Chana dal river"], ["नदी चना दाल"], ["No non-veg Thursday"], ["गुरुवार मांसाहार बचें"]),
    9: ("Extremely fortunate", "अत्यंत भाग्यशाली",
        ["Thursday Vishnu worship"], ["गुरुवार विष्णु पूजा"],
        ["Yellow rice temple Thursday"], ["गुरुवार मंदिर पीले चावल"], ["Respect holy men"], ["संतों सम्मान"]),
    10: ("Teaching/law/banking career", "शिक्षण/कानून/बैंकिंग करियर",
        ["Pukhraj index finger", "Saffron tilak"], ["तर्जनी पुखराज", "केसर तिलक"],
        ["Chana dal", "Yellow flowers"], ["चना दाल", "पीले फूल"], ["No corruption"], ["भ्रष्टाचार बचें"]),
    11: ("Gains religion/teaching", "धर्म/शिक्षण लाभ",
        ["Turmeric water Peepal"], ["पीपल हल्दी पानी"],
        ["Thursday yellow sweets"], ["गुरुवार पीली मिठाई"], ["Share knowledge"], ["ज्ञान बांटें"]),
    12: ("Spiritual liberation", "आध्यात्मिक मुक्ति",
        ["Daily temple", "Saffron tilak"], ["प्रतिदिन मंदिर", "केसर तिलक"],
        ["Yellow items ashrams"], ["आश्रमों पीली वस्तुएं"], ["Moderate worldly attachment"], ["सांसारिक आसक्ति संयम"]),
  },
  "Venus": {
    1: ("Charming, artistic, luxury", "आकर्षक, कलात्मक, विलासिता",
        ["Diamond/opal", "White items Lakshmi temple"], ["हीरा/ओपल", "लक्ष्मी मंदिर सफेद"],
        ["White rice", "Ghee", "Perfume"], ["सफेद चावल", "घी", "इत्र"], ["Moderate indulgence"], ["संयम भोग"]),
    2: ("Wealth arts/beauty", "कला/सौंदर्य धन",
        ["Silver home", "Friday white donation"], ["घर चांदी", "शुक्रवार सफेद दान"],
        ["White rice", "Sugar"], ["सफेद चावल", "चीनी"], ["Respect women"], ["महिला सम्मान"]),
    3: ("Artistic siblings, travel", "कलात्मक भाई-बहन, यात्रा",
        ["Opal", "Perfume to sister"], ["ओपल", "बहन इत्र"],
        ["White cloth"], ["सफेद कपड़ा"], ["Moral relationships"], ["नैतिक संबंध"]),
    4: ("Luxurious home, vehicles", "शानदार घर, वाहन",
        ["White flowers home", "Friday Lakshmi temple"], ["घर सफेद फूल", "शुक्रवार लक्ष्मी मंदिर"],
        ["White rice poor", "Ghee temple"], ["गरीबों चावल", "मंदिर घी"], ["Protect plants"], ["पौधे रक्षा"]),
    5: ("Romantic, creative", "रोमांटिक, रचनात्मक",
        ["White flowers Lakshmi temple"], ["लक्ष्मी मंदिर सफेद फूल"],
        ["White sweets"], ["सफेद मिठाई"], ["One faithful relationship"], ["एक विश्वसनीय संबंध"]),
    6: ("Enemies women, kidney", "महिला शत्रु, गुर्दा",
        ["Friday white donation", "Cow ghee home"], ["शुक्रवार सफेद दान", "गाय घी"],
        ["White cloth poor women"], ["गरीब महिलाओं सफेद कपड़ा"], ["No fighting women"], ["महिला लड़ाई बचें"]),
    7: ("Beautiful spouse, happy marriage", "सुंदर साथी, सुखी विवाह",
        ["White gifts spouse", "Diamond/opal"], ["जीवनसाथी सफेद उपहार", "हीरा/ओपल"],
        ["White cloth newlyweds"], ["नवविवाहितों सफेद कपड़ा"], ["Respect spouse always"], ["सदा साथी सम्मान"]),
    8: ("Hidden wealth, marriage obstacle", "गुप्त धन, विवाह बाधा",
        ["Rice+white cloth donation", "Friday ghee lamp"], ["चावल-सफेद कपड़ा दान", "शुक्रवार घी दीपक"],
        ["Friday white items river"], ["शुक्रवार नदी सफेद वस्तुएं"], ["No secret affairs"], ["गुप्त संबंध बचें"]),
    9: ("Fortune through wife/arts", "पत्नी/कला भाग्य",
        ["Friday Lakshmi temple white flowers"], ["शुक्रवार लक्ष्मी मंदिर सफेद फूल"],
        ["Ghee temple"], ["मंदिर घी"], ["Generous with wife"], ["पत्नी उदार"]),
    10: ("Arts/fashion/entertainment career", "कला/फैशन/मनोरंजन करियर",
        ["Diamond/opal ring finger"], ["अनामिका हीरा/ओपल"],
        ["White sweets Friday"], ["शुक्रवार सफेद मिठाई"], ["Work-life balance"], ["कार्य-जीवन संतुलन"]),
    11: ("Gains women/arts/beauty", "महिला/कला/सौंदर्य लाभ",
        ["Friday white donation"], ["शुक्रवार सफेद दान"],
        ["White rice poor women"], ["गरीब महिलाओं सफेद चावल"], ["Don't exploit women"], ["महिला शोषण बचें"]),
    12: ("Luxury expenditure", "विलासिता खर्च",
        ["Silver under pillow", "White flowers"], ["तकिए चांदी", "सफेद फूल"],
        ["White items ashrams"], ["आश्रमों सफेद वस्तुएं"], ["Moderate luxury spending"], ["विलासिता खर्च संयम"]),
  },
  "Saturn": {
    1: ("Hard-working, early struggles", "मेहनती, प्रारंभिक संघर्ष",
        ["Iron ring right hand", "Saturday mustard oil Shani temple"], ["दाहिना हाथ लोहे अंगूठी", "शनिवार शनि मंदिर सरसों तेल"],
        ["Mustard oil", "Black sesame", "Iron"], ["सरसों तेल", "काले तिल", "लोहा"], ["No alcohol Saturday"], ["शनिवार शराब बचें"]),
    2: ("Financial discipline", "वित्तीय अनुशासन",
        ["Iron wallet", "Feed crows"], ["बटुए लोहा", "कौवों खिलाएं"],
        ["Black urad dal", "Saturday mustard oil"], ["काली उड़द", "शनिवार सरसों तेल"], ["No lies about money"], ["पैसों झूठ बचें"]),
    3: ("Courageous, sibling strain", "साहसी, भाई-बहन तनाव",
        ["Iron donation", "Feed black dogs"], ["लोहा दान", "काले कुत्तों खिलाएं"],
        ["Saturday black sesame"], ["शनिवार काले तिल"], ["Don't cheat siblings"], ["भाई-बहन धोखा बचें"]),
    4: ("Property hard work, mother health", "मेहनत संपत्ति, माता स्वास्थ्य",
        ["Iron at entrance", "Rice to crows"], ["प्रवेश लोहा", "कौवों चावल"],
        ["Saturday mustard oil"], ["शनिवार सरसों तेल"], ["Kind to servants"], ["नौकरों दयालु"]),
    5: ("Delayed children, wisdom", "विलंबित संतान, बुद्धि",
        ["Feed crows", "Saturday iron donation"], ["कौवों खिलाएं", "शनिवार लोहा"],
        ["Black urad dal"], ["काली उड़द"], ["Kind to children"], ["बच्चों दयालु"]),
    6: ("Patient victory", "धैर्य विजय",
        ["Feed black dogs", "Iron ring"], ["काले कुत्तों खिलाएं", "लोहे अंगूठी"],
        ["Mustard oil Shani temple"], ["शनि मंदिर सरसों तेल"], ["Kind to servants"], ["नौकरों दयालु"]),
    7: ("Delayed marriage, serious spouse", "विलंबित विवाह, गंभीर साथी",
        ["Saturday black cloth", "Iron ring"], ["शनिवार काला कपड़ा", "लोहे अंगूठी"],
        ["Black urad dal poor"], ["गरीबों काली उड़द"], ["Respect spouse"], ["साथी सम्मान"]),
    8: ("Longevity through suffering", "कष्ट दीर्घायु",
        ["Saturday sesame river", "Feed crows"], ["शनिवार नदी तिल", "कौवों खिलाएं"],
        ["Mustard oil", "Iron river"], ["सरसों तेल", "नदी लोहा"], ["No stale food home"], ["घर बासी भोजन बचें"]),
    9: ("Fortune through discipline", "अनुशासन भाग्य",
        ["Saturday Shani temple", "Black sesame donation"], ["शनिवार शनि मंदिर", "काले तिल दान"],
        ["Saturday urad dal temple"], ["शनिवार मंदिर उड़द"], ["Respect workers"], ["कामगारों सम्मान"]),
    10: ("Hard-work career, govt/law", "मेहनत करियर, सरकार/कानून",
        ["Blue Sapphire if suitable", "Saturday Shani temple"], ["उपयुक्त हो नीलम", "शनिवार शनि मंदिर"],
        ["Mustard oil", "Black cloth"], ["सरसों तेल", "काला कपड़ा"], ["Don't exploit workers"], ["कामगारों शोषण बचें"]),
    11: ("Disciplined gains", "अनुशासन लाभ",
        ["Iron donation", "Saturday crows feed"], ["लोहा दान", "शनिवार कौवों खिलाएं"],
        ["Saturday black sesame"], ["शनिवार काले तिल"], ["Don't betray old friends"], ["पुराने मित्र विश्वासघात बचें"]),
    12: ("Spiritual detachment", "आध्यात्मिक वैराग्य",
        ["Saturday sesame lamp Shani temple"], ["शनिवार शनि मंदिर तिल दीपक"],
        ["Iron", "Black cloth beggars"], ["लोहा", "भिखारियों काला कपड़ा"], ["Kind to animals"], ["पशुओं दयालु"]),
  },
  "Rahu": {
    1: ("Unconventional, foreign links", "अपरंपरागत, विदेशी संबंध",
        ["Silver ball", "Donate barley"], ["चांदी गोली", "जौ दान"],
        ["Coconut river", "Barley"], ["नदी नारियल", "जौ"], ["No intoxicants"], ["नशा बचें"]),
    2: ("Sudden wealth/loss", "अचानक धन/हानि",
        ["Lead/silver ball", "Feed birds"], ["सीसा/चांदी गोली", "पक्षियों खिलाएं"],
        ["Coconut flowing water"], ["बहते पानी नारियल"], ["No lies"], ["झूठ बचें"]),
    3: ("Brave but confused", "बहादुर लेकिन भ्रमित",
        ["Silver items", "Saturday barley"], ["चांदी", "शनिवार जौ"],
        ["Barley", "Coconut"], ["जौ", "नारियल"], ["No gambling"], ["जुआ बचें"]),
    4: ("Sudden property gain/loss", "अचानक संपत्ति लाभ/हानि",
        ["Silver square entrance", "Barley flowing water"], ["प्रवेश चांदी चौकोर", "बहते पानी जौ"],
        ["Coconut Saturday"], ["शनिवार नारियल"], ["No electronics under pillow"], ["तकिए इलेक्ट्रॉनिक बचें"]),
    5: ("Unconventional education", "अपरंपरागत शिक्षा",
        ["Silver items", "Coconut river"], ["चांदी", "नदी नारियल"],
        ["Barley poor"], ["गरीबों जौ"], ["No speculation"], ["सट्टा बचें"]),
    6: ("Victory hidden enemies", "छिपे शत्रु विजय",
        ["Lead ball", "Barley donation"], ["सीसा गोली", "जौ दान"],
        ["Barley+coconut river"], ["नदी जौ-नारियल"], ["No black magic"], ["काला जादू बचें"]),
    7: ("Foreign/unconventional spouse", "विदेशी/अपरंपरागत साथी",
        ["Silver items", "Saturday coconut float"], ["चांदी", "शनिवार नारियल बहाएं"],
        ["Coconut temple"], ["मंदिर नारियल"], ["No marriage deception"], ["विवाह छल बचें"]),
    8: ("Sudden events, occult", "अचानक घटनाएं, तांत्रिक",
        ["Silver", "Barley river"], ["चांदी", "नदी जौ"],
        ["Saturday coconut+barley river"], ["शनिवार नदी नारियल-जौ"], ["No risky behaviour"], ["जोखिम बचें"]),
    9: ("Foreign travel, beliefs", "विदेश यात्रा, विश्वास",
        ["Barley temple", "Silver worship place"], ["मंदिर जौ", "पूजा चांदी"],
        ["Saturday coconut temple"], ["शनिवार मंदिर नारियल"], ["Respect all religions"], ["सभी धर्म सम्मान"]),
    10: ("Foreign/tech career", "विदेशी/तकनीकी करियर",
        ["Silver workplace", "Coconut donation"], ["कार्यस्थल चांदी", "नारियल दान"],
        ["Saturday barley+coconut"], ["शनिवार जौ-नारियल"], ["No unethical shortcuts"], ["अनैतिक शॉर्टकट बचें"]),
    11: ("Sudden large gains", "अचानक बड़ा लाभ",
        ["Silver", "Saturday barley"], ["चांदी", "शनिवार जौ"],
        ["Coconut river"], ["नदी नारियल"], ["Don't betray friends"], ["मित्र विश्वासघात बचें"]),
    12: ("Foreign settlement", "विदेश बसावट",
        ["Coconut+barley river", "Silver bed"], ["नदी नारियल-जौ", "बिस्तर चांदी"],
        ["Barley temple"], ["मंदिर जौ"], ["No intoxicants/black magic"], ["नशा/काला जादू बचें"]),
  },
  "Ketu": {
    1: ("Spiritual, detached", "आध्यात्मिक, विरक्त",
        ["Feed stray dogs", "Donate blankets"], ["आवारा कुत्तों खिलाएं", "कंबल दान"],
        ["Black+white sesame", "Blankets poor"], ["काले-सफेद तिल", "गरीबों कंबल"], ["Don't tie stray dogs"], ["आवारा कुत्ते न बांधें"]),
    2: ("Sudden losses, mystical speech", "अचानक हानि, रहस्यमय वाणी",
        ["Feed dogs", "Saffron home"], ["कुत्तों खिलाएं", "घर केसर"],
        ["Blanket poor"], ["गरीबों कंबल"], ["No lies"], ["झूठ बचें"]),
    3: ("Spiritual courage, occult", "आध्यात्मिक साहस, तांत्रिक",
        ["Blankets donation", "Daily dogs feed"], ["कंबल दान", "प्रतिदिन कुत्तों खिलाएं"],
        ["Sesame temple"], ["मंदिर तिल"], ["No black magic"], ["काला जादू बचें"]),
    4: ("Detached from home", "घर से विरक्त",
        ["Keep dog home", "Blankets old-age home"], ["घर कुत्ता", "वृद्धाश्रम कंबल"],
        ["Blankets", "Black sesame"], ["कंबल", "काले तिल"], ["Respect mother"], ["माता सम्मान"]),
    5: ("Spiritual children", "आध्यात्मिक संतान",
        ["Feed stray dogs", "Orphanage donation"], ["आवारा कुत्तों खिलाएं", "अनाथालय दान"],
        ["Blankets children"], ["बच्चों कंबल"], ["Kind to animals"], ["पशुओं दयालु"]),
    6: ("Spiritual victory, skin", "आध्यात्मिक विजय, त्वचा",
        ["Feed black+white dogs"], ["काले-सफेद कुत्तों खिलाएं"],
        ["Blankets hospital workers"], ["अस्पताल कर्मचारियों कंबल"], ["No negative energy"], ["नकारात्मक ऊर्जा बचें"]),
    7: ("Spiritual spouse", "आध्यात्मिक साथी",
        ["Feed dogs with spouse", "Blankets donation"], ["साथी संग कुत्तों खिलाएं", "कंबल दान"],
        ["Black+white cloth couple"], ["जोड़े काला-सफेद कपड़ा"], ["Respect spouse spirituality"], ["साथी आध्यात्मिकता सम्मान"]),
    8: ("Deep mystical knowledge", "गहरा रहस्यमय ज्ञान",
        ["Sesame river", "Feed stray dogs"], ["नदी तिल", "आवारा कुत्तों खिलाएं"],
        ["Blankets+sesame temple"], ["मंदिर कंबल-तिल"], ["No occult without guide"], ["बिना गुरु तांत्रिक बचें"]),
    9: ("Pilgrimages, past karma", "तीर्थयात्रा, पूर्व कर्म",
        ["Visit spiritual places", "Feed temple dogs"], ["आध्यात्मिक स्थल", "मंदिर कुत्तों खिलाएं"],
        ["Blankets ashrams"], ["आश्रमों कंबल"], ["Respect all religions"], ["सभी धर्म सम्मान"]),
    10: ("Spiritual/research/detective career", "आध्यात्मिक/शोध/जासूसी करियर",
        ["Feed dogs workplace", "Blankets donation"], ["कार्यस्थल कुत्तों खिलाएं", "कंबल दान"],
        ["Blankets workers"], ["कामगारों कंबल"], ["Honest work"], ["ईमानदार कार्य"]),
    11: ("Spiritual gains", "आध्यात्मिकता लाभ",
        ["Blankets donation", "Feed dogs"], ["कंबल दान", "कुत्तों खिलाएं"],
        ["Sesame temple"], ["मंदिर तिल"], ["Don't cheat spiritual friends"], ["आध्यात्मिक मित्र धोखा बचें"]),
    12: ("Moksha, liberation", "मोक्ष, मुक्ति",
        ["Daily dogs feed", "Blankets homeless"], ["प्रतिदिन कुत्तों खिलाएं", "बेघरों कंबल"],
        ["Blankets+food ashrams"], ["आश्रमों कंबल-भोजन"], ["Moderate isolation"], ["संयम एकांत"]),
  },
}
